import "dotenv/config";

const PORT = process.env.PORT;
const HOST = process.env.HOST;
const GOOGLE_APPLICATION_CREDENTIALS =
  process.env.GOOGLE_APPLICATION_CREDENTIALS;
const FIREBASE_TOKEN = process.env.FIREBASE_TOKEN;
const FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY;
const FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID;
const FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL;
const TEST_FIREBASE_API_KEY = process.env.TEST_FIREBASE_API_KEY;

export {
  PORT,
  HOST,
  GOOGLE_APPLICATION_CREDENTIALS,
  FIREBASE_TOKEN,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL,
  TEST_FIREBASE_API_KEY,
};
